extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 80
    level: warning

ignore: |
  component/dependencies/
  component/helmcharts/
  component/manifests/
  component/vendor/
  component/compiled/
